package com.tstar.dao.tapp;

import com.tstar.model.tapp.FormData;
import com.tstar.model.tapp.FormDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FormDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORM_DATA
     *
     * @mbggenerated Tue Mar 03 16:25:54 CST 2015
     */
    int countByExample(FormDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORM_DATA
     *
     * @mbggenerated Tue Mar 03 16:25:54 CST 2015
     */
    int deleteByExample(FormDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORM_DATA
     *
     * @mbggenerated Tue Mar 03 16:25:54 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORM_DATA
     *
     * @mbggenerated Tue Mar 03 16:25:54 CST 2015
     */
    int insert(FormData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORM_DATA
     *
     * @mbggenerated Tue Mar 03 16:25:54 CST 2015
     */
    int insertSelective(FormData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORM_DATA
     *
     * @mbggenerated Tue Mar 03 16:25:54 CST 2015
     */
    List<FormData> selectByExample(FormDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORM_DATA
     *
     * @mbggenerated Tue Mar 03 16:25:54 CST 2015
     */
    FormData selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORM_DATA
     *
     * @mbggenerated Tue Mar 03 16:25:54 CST 2015
     */
    int updateByExampleSelective(@Param("record") FormData record, @Param("example") FormDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORM_DATA
     *
     * @mbggenerated Tue Mar 03 16:25:54 CST 2015
     */
    int updateByExample(@Param("record") FormData record, @Param("example") FormDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORM_DATA
     *
     * @mbggenerated Tue Mar 03 16:25:54 CST 2015
     */
    int updateByPrimaryKeySelective(FormData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORM_DATA
     *
     * @mbggenerated Tue Mar 03 16:25:54 CST 2015
     */
    int updateByPrimaryKey(FormData record);
}