package com.tstar.dao.tapp;

import com.tstar.model.tapp.MvMessageList;
import com.tstar.model.tapp.MvMessageListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MvMessageListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_MESSAGELIST
     *
     * @mbggenerated Wed Sep 30 11:19:36 CST 2015
     */
    int countByExample(MvMessageListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_MESSAGELIST
     *
     * @mbggenerated Wed Sep 30 11:19:36 CST 2015
     */
    int deleteByExample(MvMessageListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_MESSAGELIST
     *
     * @mbggenerated Wed Sep 30 11:19:36 CST 2015
     */
    int deleteByPrimaryKey(String messageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_MESSAGELIST
     *
     * @mbggenerated Wed Sep 30 11:19:36 CST 2015
     */
    int insert(MvMessageList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_MESSAGELIST
     *
     * @mbggenerated Wed Sep 30 11:19:36 CST 2015
     */
    int insertSelective(MvMessageList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_MESSAGELIST
     *
     * @mbggenerated Wed Sep 30 11:19:36 CST 2015
     */
    List<MvMessageList> selectByExample(MvMessageListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_MESSAGELIST
     *
     * @mbggenerated Wed Sep 30 11:19:36 CST 2015
     */
    MvMessageList selectByPrimaryKey(String messageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_MESSAGELIST
     *
     * @mbggenerated Wed Sep 30 11:19:36 CST 2015
     */
    int updateByExampleSelective(@Param("record") MvMessageList record, @Param("example") MvMessageListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_MESSAGELIST
     *
     * @mbggenerated Wed Sep 30 11:19:36 CST 2015
     */
    int updateByExample(@Param("record") MvMessageList record, @Param("example") MvMessageListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_MESSAGELIST
     *
     * @mbggenerated Wed Sep 30 11:19:36 CST 2015
     */
    int updateByPrimaryKeySelective(MvMessageList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_MESSAGELIST
     *
     * @mbggenerated Wed Sep 30 11:19:36 CST 2015
     */
    int updateByPrimaryKey(MvMessageList record);
}