package com.tstar.dao.tapp;

import com.tstar.model.tapp.MvPushMessageRecordMain;
import com.tstar.model.tapp.MvPushMessageRecordMainExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MvPushMessageRecordMainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_PUSHMESSAGERECORDMAIN
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    int countByExample(MvPushMessageRecordMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_PUSHMESSAGERECORDMAIN
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    int deleteByExample(MvPushMessageRecordMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_PUSHMESSAGERECORDMAIN
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    int deleteByPrimaryKey(String messageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_PUSHMESSAGERECORDMAIN
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    int insert(MvPushMessageRecordMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_PUSHMESSAGERECORDMAIN
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    int insertSelective(MvPushMessageRecordMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_PUSHMESSAGERECORDMAIN
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    List<MvPushMessageRecordMain> selectByExample(MvPushMessageRecordMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_PUSHMESSAGERECORDMAIN
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    MvPushMessageRecordMain selectByPrimaryKey(String messageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_PUSHMESSAGERECORDMAIN
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    int updateByExampleSelective(@Param("record") MvPushMessageRecordMain record, @Param("example") MvPushMessageRecordMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_PUSHMESSAGERECORDMAIN
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    int updateByExample(@Param("record") MvPushMessageRecordMain record, @Param("example") MvPushMessageRecordMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_PUSHMESSAGERECORDMAIN
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    int updateByPrimaryKeySelective(MvPushMessageRecordMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_PUSHMESSAGERECORDMAIN
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    int updateByPrimaryKey(MvPushMessageRecordMain record);
}