package com.tstar.dao.tapp;

import com.tstar.model.tapp.MvPushMessageUsers;
import com.tstar.model.tapp.MvPushMessageUsersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MvPushMessageUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_PUSHMESSAGEUSERS
     *
     * @mbggenerated Tue Feb 24 16:04:12 CST 2015
     */
    int countByExample(MvPushMessageUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_PUSHMESSAGEUSERS
     *
     * @mbggenerated Tue Feb 24 16:04:12 CST 2015
     */
    int deleteByExample(MvPushMessageUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_PUSHMESSAGEUSERS
     *
     * @mbggenerated Tue Feb 24 16:04:12 CST 2015
     */
    int insert(MvPushMessageUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_PUSHMESSAGEUSERS
     *
     * @mbggenerated Tue Feb 24 16:04:12 CST 2015
     */
    int insertSelective(MvPushMessageUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_PUSHMESSAGEUSERS
     *
     * @mbggenerated Tue Feb 24 16:04:12 CST 2015
     */
    List<MvPushMessageUsers> selectByExample(MvPushMessageUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_PUSHMESSAGEUSERS
     *
     * @mbggenerated Tue Feb 24 16:04:12 CST 2015
     */
    int updateByExampleSelective(@Param("record") MvPushMessageUsers record, @Param("example") MvPushMessageUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_PUSHMESSAGEUSERS
     *
     * @mbggenerated Tue Feb 24 16:04:12 CST 2015
     */
    int updateByExample(@Param("record") MvPushMessageUsers record, @Param("example") MvPushMessageUsersExample example);
}