package com.tstar.dao.tapp;

import com.tstar.model.tapp.TelecomRate;
import com.tstar.model.tapp.TelecomRateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TelecomRateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TELECOM_RATE
     *
     * @mbggenerated Thu Nov 27 14:58:27 CST 2014
     */
    int countByExample(TelecomRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TELECOM_RATE
     *
     * @mbggenerated Thu Nov 27 14:58:27 CST 2014
     */
    int deleteByExample(TelecomRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TELECOM_RATE
     *
     * @mbggenerated Thu Nov 27 14:58:27 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TELECOM_RATE
     *
     * @mbggenerated Thu Nov 27 14:58:27 CST 2014
     */
    int insert(TelecomRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TELECOM_RATE
     *
     * @mbggenerated Thu Nov 27 14:58:27 CST 2014
     */
    int insertSelective(TelecomRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TELECOM_RATE
     *
     * @mbggenerated Thu Nov 27 14:58:27 CST 2014
     */
    List<TelecomRate> selectByExample(TelecomRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TELECOM_RATE
     *
     * @mbggenerated Thu Nov 27 14:58:27 CST 2014
     */
    TelecomRate selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TELECOM_RATE
     *
     * @mbggenerated Thu Nov 27 14:58:27 CST 2014
     */
    int updateByExampleSelective(@Param("record") TelecomRate record, @Param("example") TelecomRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TELECOM_RATE
     *
     * @mbggenerated Thu Nov 27 14:58:27 CST 2014
     */
    int updateByExample(@Param("record") TelecomRate record, @Param("example") TelecomRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TELECOM_RATE
     *
     * @mbggenerated Thu Nov 27 14:58:27 CST 2014
     */
    int updateByPrimaryKeySelective(TelecomRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TELECOM_RATE
     *
     * @mbggenerated Thu Nov 27 14:58:27 CST 2014
     */
    int updateByPrimaryKey(TelecomRate record);
}