package com.tstar.dao.tapp;

import com.tstar.model.tapp.TransactionLog;
import com.tstar.model.tapp.TransactionLogExample;
import com.tstar.model.tapp.TransactionLogKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransactionLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSACTION_LOG
     *
     * @mbggenerated Tue Dec 08 13:42:56 CST 2015
     */
    int countByExample(TransactionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSACTION_LOG
     *
     * @mbggenerated Tue Dec 08 13:42:56 CST 2015
     */
    int deleteByExample(TransactionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSACTION_LOG
     *
     * @mbggenerated Tue Dec 08 13:42:56 CST 2015
     */
    int deleteByPrimaryKey(TransactionLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSACTION_LOG
     *
     * @mbggenerated Tue Dec 08 13:42:56 CST 2015
     */
    int insert(TransactionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSACTION_LOG
     *
     * @mbggenerated Tue Dec 08 13:42:56 CST 2015
     */
    int insertSelective(TransactionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSACTION_LOG
     *
     * @mbggenerated Tue Dec 08 13:42:56 CST 2015
     */
    List<TransactionLog> selectByExample(TransactionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSACTION_LOG
     *
     * @mbggenerated Tue Dec 08 13:42:56 CST 2015
     */
    TransactionLog selectByPrimaryKey(TransactionLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSACTION_LOG
     *
     * @mbggenerated Tue Dec 08 13:42:56 CST 2015
     */
    int updateByExampleSelective(@Param("record") TransactionLog record, @Param("example") TransactionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSACTION_LOG
     *
     * @mbggenerated Tue Dec 08 13:42:56 CST 2015
     */
    int updateByExample(@Param("record") TransactionLog record, @Param("example") TransactionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSACTION_LOG
     *
     * @mbggenerated Tue Dec 08 13:42:56 CST 2015
     */
    int updateByPrimaryKeySelective(TransactionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSACTION_LOG
     *
     * @mbggenerated Tue Dec 08 13:42:56 CST 2015
     */
    int updateByPrimaryKey(TransactionLog record);
}