package com.tstar.model.sms;

import java.util.Date;

public class SmsReqList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMSREQLIST.SIEBEL_ID
     *
     * @mbggenerated Tue Sep 02 10:48:06 CST 2014
     */
    private String siebelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMSREQLIST.MSISDN
     *
     * @mbggenerated Tue Sep 02 10:48:06 CST 2014
     */
    private String msisdn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMSREQLIST.MSGTEXT
     *
     * @mbggenerated Tue Sep 02 10:48:06 CST 2014
     */
    private String msgtext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMSREQLIST.APPLYTIME
     *
     * @mbggenerated Tue Sep 02 10:48:06 CST 2014
     */
    private Date applytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMSREQLIST.AGREETIME
     *
     * @mbggenerated Tue Sep 02 10:48:06 CST 2014
     */
    private Date agreetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMSREQLIST.SMSTYPE
     *
     * @mbggenerated Tue Sep 02 10:48:06 CST 2014
     */
    private String smstype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMSREQLIST.SMSSOURCE
     *
     * @mbggenerated Tue Sep 02 10:48:06 CST 2014
     */
    private String smssource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMSREQLIST.STATUS
     *
     * @mbggenerated Tue Sep 02 10:48:06 CST 2014
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMSREQLIST.COMPANY_NAME
     *
     * @mbggenerated Tue Sep 02 10:48:06 CST 2014
     */
    private String companyName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMSREQLIST.SIEBEL_ID
     *
     * @return the value of SMSREQLIST.SIEBEL_ID
     *
     * @mbggenerated Tue Sep 02 10:48:06 CST 2014
     */
    public String getSiebelId() {
        return siebelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMSREQLIST.SIEBEL_ID
     *
     * @param siebelId the value for SMSREQLIST.SIEBEL_ID
     *
     * @mbggenerated Tue Sep 02 10:48:06 CST 2014
     */
    public void setSiebelId(String siebelId) {
        this.siebelId = siebelId == null ? null : siebelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMSREQLIST.MSISDN
     *
     * @return the value of SMSREQLIST.MSISDN
     *
     * @mbggenerated Tue Sep 02 10:48:06 CST 2014
     */
    public String getMsisdn() {
        return msisdn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMSREQLIST.MSISDN
     *
     * @param msisdn the value for SMSREQLIST.MSISDN
     *
     * @mbggenerated Tue Sep 02 10:48:06 CST 2014
     */
    public void setMsisdn(String msisdn) {
        this.msisdn = msisdn == null ? null : msisdn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMSREQLIST.MSGTEXT
     *
     * @return the value of SMSREQLIST.MSGTEXT
     *
     * @mbggenerated Tue Sep 02 10:48:06 CST 2014
     */
    public String getMsgtext() {
        return msgtext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMSREQLIST.MSGTEXT
     *
     * @param msgtext the value for SMSREQLIST.MSGTEXT
     *
     * @mbggenerated Tue Sep 02 10:48:06 CST 2014
     */
    public void setMsgtext(String msgtext) {
        this.msgtext = msgtext == null ? null : msgtext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMSREQLIST.APPLYTIME
     *
     * @return the value of SMSREQLIST.APPLYTIME
     *
     * @mbggenerated Tue Sep 02 10:48:06 CST 2014
     */
    public Date getApplytime() {
        return applytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMSREQLIST.APPLYTIME
     *
     * @param applytime the value for SMSREQLIST.APPLYTIME
     *
     * @mbggenerated Tue Sep 02 10:48:06 CST 2014
     */
    public void setApplytime(Date applytime) {
        this.applytime = applytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMSREQLIST.AGREETIME
     *
     * @return the value of SMSREQLIST.AGREETIME
     *
     * @mbggenerated Tue Sep 02 10:48:06 CST 2014
     */
    public Date getAgreetime() {
        return agreetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMSREQLIST.AGREETIME
     *
     * @param agreetime the value for SMSREQLIST.AGREETIME
     *
     * @mbggenerated Tue Sep 02 10:48:06 CST 2014
     */
    public void setAgreetime(Date agreetime) {
        this.agreetime = agreetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMSREQLIST.SMSTYPE
     *
     * @return the value of SMSREQLIST.SMSTYPE
     *
     * @mbggenerated Tue Sep 02 10:48:06 CST 2014
     */
    public String getSmstype() {
        return smstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMSREQLIST.SMSTYPE
     *
     * @param smstype the value for SMSREQLIST.SMSTYPE
     *
     * @mbggenerated Tue Sep 02 10:48:06 CST 2014
     */
    public void setSmstype(String smstype) {
        this.smstype = smstype == null ? null : smstype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMSREQLIST.SMSSOURCE
     *
     * @return the value of SMSREQLIST.SMSSOURCE
     *
     * @mbggenerated Tue Sep 02 10:48:06 CST 2014
     */
    public String getSmssource() {
        return smssource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMSREQLIST.SMSSOURCE
     *
     * @param smssource the value for SMSREQLIST.SMSSOURCE
     *
     * @mbggenerated Tue Sep 02 10:48:06 CST 2014
     */
    public void setSmssource(String smssource) {
        this.smssource = smssource == null ? null : smssource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMSREQLIST.STATUS
     *
     * @return the value of SMSREQLIST.STATUS
     *
     * @mbggenerated Tue Sep 02 10:48:06 CST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMSREQLIST.STATUS
     *
     * @param status the value for SMSREQLIST.STATUS
     *
     * @mbggenerated Tue Sep 02 10:48:06 CST 2014
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMSREQLIST.COMPANY_NAME
     *
     * @return the value of SMSREQLIST.COMPANY_NAME
     *
     * @mbggenerated Tue Sep 02 10:48:06 CST 2014
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMSREQLIST.COMPANY_NAME
     *
     * @param companyName the value for SMSREQLIST.COMPANY_NAME
     *
     * @mbggenerated Tue Sep 02 10:48:06 CST 2014
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }
}