package com.tstar.model.tapp;

import java.sql.Timestamp;

public class CommercialReference {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMERCIAL_REFERENCE.ID
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMERCIAL_REFERENCE.MSISDN
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    private String msisdn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMERCIAL_REFERENCE.CONTRACT_ID
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    private String contractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMERCIAL_REFERENCE.ACTION
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    private String action;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMERCIAL_REFERENCE.SOURCE_ID
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    private String sourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMERCIAL_REFERENCE.SOURCE_IP
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    private String sourceIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMERCIAL_REFERENCE.MEMO1
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    private String memo1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMERCIAL_REFERENCE.MEMO2
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    private String memo2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMERCIAL_REFERENCE.STATUS
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMERCIAL_REFERENCE.CREATE_USER
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMERCIAL_REFERENCE.CREATE_TIME
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMERCIAL_REFERENCE.UPDATE_USER
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMERCIAL_REFERENCE.UPDATE_TIME
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    private Timestamp updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMERCIAL_REFERENCE.ID
     *
     * @return the value of COMMERCIAL_REFERENCE.ID
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMERCIAL_REFERENCE.ID
     *
     * @param id the value for COMMERCIAL_REFERENCE.ID
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMERCIAL_REFERENCE.MSISDN
     *
     * @return the value of COMMERCIAL_REFERENCE.MSISDN
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    public String getMsisdn() {
        return msisdn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMERCIAL_REFERENCE.MSISDN
     *
     * @param msisdn the value for COMMERCIAL_REFERENCE.MSISDN
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    public void setMsisdn(String msisdn) {
        this.msisdn = msisdn == null ? null : msisdn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMERCIAL_REFERENCE.CONTRACT_ID
     *
     * @return the value of COMMERCIAL_REFERENCE.CONTRACT_ID
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    public String getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMERCIAL_REFERENCE.CONTRACT_ID
     *
     * @param contractId the value for COMMERCIAL_REFERENCE.CONTRACT_ID
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    public void setContractId(String contractId) {
        this.contractId = contractId == null ? null : contractId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMERCIAL_REFERENCE.ACTION
     *
     * @return the value of COMMERCIAL_REFERENCE.ACTION
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMERCIAL_REFERENCE.ACTION
     *
     * @param action the value for COMMERCIAL_REFERENCE.ACTION
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMERCIAL_REFERENCE.SOURCE_ID
     *
     * @return the value of COMMERCIAL_REFERENCE.SOURCE_ID
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    public String getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMERCIAL_REFERENCE.SOURCE_ID
     *
     * @param sourceId the value for COMMERCIAL_REFERENCE.SOURCE_ID
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    public void setSourceId(String sourceId) {
        this.sourceId = sourceId == null ? null : sourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMERCIAL_REFERENCE.SOURCE_IP
     *
     * @return the value of COMMERCIAL_REFERENCE.SOURCE_IP
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    public String getSourceIp() {
        return sourceIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMERCIAL_REFERENCE.SOURCE_IP
     *
     * @param sourceIp the value for COMMERCIAL_REFERENCE.SOURCE_IP
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    public void setSourceIp(String sourceIp) {
        this.sourceIp = sourceIp == null ? null : sourceIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMERCIAL_REFERENCE.MEMO1
     *
     * @return the value of COMMERCIAL_REFERENCE.MEMO1
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    public String getMemo1() {
        return memo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMERCIAL_REFERENCE.MEMO1
     *
     * @param memo1 the value for COMMERCIAL_REFERENCE.MEMO1
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    public void setMemo1(String memo1) {
        this.memo1 = memo1 == null ? null : memo1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMERCIAL_REFERENCE.MEMO2
     *
     * @return the value of COMMERCIAL_REFERENCE.MEMO2
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    public String getMemo2() {
        return memo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMERCIAL_REFERENCE.MEMO2
     *
     * @param memo2 the value for COMMERCIAL_REFERENCE.MEMO2
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    public void setMemo2(String memo2) {
        this.memo2 = memo2 == null ? null : memo2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMERCIAL_REFERENCE.STATUS
     *
     * @return the value of COMMERCIAL_REFERENCE.STATUS
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMERCIAL_REFERENCE.STATUS
     *
     * @param status the value for COMMERCIAL_REFERENCE.STATUS
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMERCIAL_REFERENCE.CREATE_USER
     *
     * @return the value of COMMERCIAL_REFERENCE.CREATE_USER
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMERCIAL_REFERENCE.CREATE_USER
     *
     * @param createUser the value for COMMERCIAL_REFERENCE.CREATE_USER
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMERCIAL_REFERENCE.CREATE_TIME
     *
     * @return the value of COMMERCIAL_REFERENCE.CREATE_TIME
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMERCIAL_REFERENCE.CREATE_TIME
     *
     * @param createTime the value for COMMERCIAL_REFERENCE.CREATE_TIME
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMERCIAL_REFERENCE.UPDATE_USER
     *
     * @return the value of COMMERCIAL_REFERENCE.UPDATE_USER
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMERCIAL_REFERENCE.UPDATE_USER
     *
     * @param updateUser the value for COMMERCIAL_REFERENCE.UPDATE_USER
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMERCIAL_REFERENCE.UPDATE_TIME
     *
     * @return the value of COMMERCIAL_REFERENCE.UPDATE_TIME
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMERCIAL_REFERENCE.UPDATE_TIME
     *
     * @param updateTime the value for COMMERCIAL_REFERENCE.UPDATE_TIME
     *
     * @mbggenerated Wed Mar 18 16:33:26 CST 2015
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }
}