package com.tstar.model.tapp;

public class Devices {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICES.ID
     *
     * @mbggenerated Wed Oct 01 17:36:16 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICES.NAME
     *
     * @mbggenerated Wed Oct 01 17:36:16 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICES.DEVICE_MODEL
     *
     * @mbggenerated Wed Oct 01 17:36:16 CST 2014
     */
    private String deviceModel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICES.ID
     *
     * @return the value of DEVICES.ID
     *
     * @mbggenerated Wed Oct 01 17:36:16 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICES.ID
     *
     * @param id the value for DEVICES.ID
     *
     * @mbggenerated Wed Oct 01 17:36:16 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICES.NAME
     *
     * @return the value of DEVICES.NAME
     *
     * @mbggenerated Wed Oct 01 17:36:16 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICES.NAME
     *
     * @param name the value for DEVICES.NAME
     *
     * @mbggenerated Wed Oct 01 17:36:16 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICES.DEVICE_MODEL
     *
     * @return the value of DEVICES.DEVICE_MODEL
     *
     * @mbggenerated Wed Oct 01 17:36:16 CST 2014
     */
    public String getDeviceModel() {
        return deviceModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICES.DEVICE_MODEL
     *
     * @param deviceModel the value for DEVICES.DEVICE_MODEL
     *
     * @mbggenerated Wed Oct 01 17:36:16 CST 2014
     */
    public void setDeviceModel(String deviceModel) {
        this.deviceModel = deviceModel == null ? null : deviceModel.trim();
    }
}