package com.tstar.model.tapp;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class MvMessageListExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MV_MESSAGELIST
     *
     * @mbggenerated Wed Sep 30 11:19:36 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MV_MESSAGELIST
     *
     * @mbggenerated Wed Sep 30 11:19:36 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MV_MESSAGELIST
     *
     * @mbggenerated Wed Sep 30 11:19:36 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_MESSAGELIST
     *
     * @mbggenerated Wed Sep 30 11:19:36 CST 2015
     */
    public MvMessageListExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_MESSAGELIST
     *
     * @mbggenerated Wed Sep 30 11:19:36 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_MESSAGELIST
     *
     * @mbggenerated Wed Sep 30 11:19:36 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_MESSAGELIST
     *
     * @mbggenerated Wed Sep 30 11:19:36 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_MESSAGELIST
     *
     * @mbggenerated Wed Sep 30 11:19:36 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_MESSAGELIST
     *
     * @mbggenerated Wed Sep 30 11:19:36 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_MESSAGELIST
     *
     * @mbggenerated Wed Sep 30 11:19:36 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_MESSAGELIST
     *
     * @mbggenerated Wed Sep 30 11:19:36 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_MESSAGELIST
     *
     * @mbggenerated Wed Sep 30 11:19:36 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_MESSAGELIST
     *
     * @mbggenerated Wed Sep 30 11:19:36 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MV_MESSAGELIST
     *
     * @mbggenerated Wed Sep 30 11:19:36 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MV_MESSAGELIST
     *
     * @mbggenerated Wed Sep 30 11:19:36 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andMessageidIsNull() {
            addCriterion("MESSAGEID is null");
            return (Criteria) this;
        }

        public Criteria andMessageidIsNotNull() {
            addCriterion("MESSAGEID is not null");
            return (Criteria) this;
        }

        public Criteria andMessageidEqualTo(String value) {
            addCriterion("MESSAGEID =", value, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidNotEqualTo(String value) {
            addCriterion("MESSAGEID <>", value, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidGreaterThan(String value) {
            addCriterion("MESSAGEID >", value, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidGreaterThanOrEqualTo(String value) {
            addCriterion("MESSAGEID >=", value, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidLessThan(String value) {
            addCriterion("MESSAGEID <", value, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidLessThanOrEqualTo(String value) {
            addCriterion("MESSAGEID <=", value, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidLike(String value) {
            addCriterion("MESSAGEID like", value, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidNotLike(String value) {
            addCriterion("MESSAGEID not like", value, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidIn(List<String> values) {
            addCriterion("MESSAGEID in", values, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidNotIn(List<String> values) {
            addCriterion("MESSAGEID not in", values, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidBetween(String value1, String value2) {
            addCriterion("MESSAGEID between", value1, value2, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidNotBetween(String value1, String value2) {
            addCriterion("MESSAGEID not between", value1, value2, "messageid");
            return (Criteria) this;
        }

        public Criteria andVersionnoIsNull() {
            addCriterion("VERSIONNO is null");
            return (Criteria) this;
        }

        public Criteria andVersionnoIsNotNull() {
            addCriterion("VERSIONNO is not null");
            return (Criteria) this;
        }

        public Criteria andVersionnoEqualTo(BigDecimal value) {
            addCriterion("VERSIONNO =", value, "versionno");
            return (Criteria) this;
        }

        public Criteria andVersionnoNotEqualTo(BigDecimal value) {
            addCriterion("VERSIONNO <>", value, "versionno");
            return (Criteria) this;
        }

        public Criteria andVersionnoGreaterThan(BigDecimal value) {
            addCriterion("VERSIONNO >", value, "versionno");
            return (Criteria) this;
        }

        public Criteria andVersionnoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VERSIONNO >=", value, "versionno");
            return (Criteria) this;
        }

        public Criteria andVersionnoLessThan(BigDecimal value) {
            addCriterion("VERSIONNO <", value, "versionno");
            return (Criteria) this;
        }

        public Criteria andVersionnoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("VERSIONNO <=", value, "versionno");
            return (Criteria) this;
        }

        public Criteria andVersionnoIn(List<BigDecimal> values) {
            addCriterion("VERSIONNO in", values, "versionno");
            return (Criteria) this;
        }

        public Criteria andVersionnoNotIn(List<BigDecimal> values) {
            addCriterion("VERSIONNO not in", values, "versionno");
            return (Criteria) this;
        }

        public Criteria andVersionnoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VERSIONNO between", value1, value2, "versionno");
            return (Criteria) this;
        }

        public Criteria andVersionnoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VERSIONNO not between", value1, value2, "versionno");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andLastmodifiedpersonIsNull() {
            addCriterion("LASTMODIFIEDPERSON is null");
            return (Criteria) this;
        }

        public Criteria andLastmodifiedpersonIsNotNull() {
            addCriterion("LASTMODIFIEDPERSON is not null");
            return (Criteria) this;
        }

        public Criteria andLastmodifiedpersonEqualTo(String value) {
            addCriterion("LASTMODIFIEDPERSON =", value, "lastmodifiedperson");
            return (Criteria) this;
        }

        public Criteria andLastmodifiedpersonNotEqualTo(String value) {
            addCriterion("LASTMODIFIEDPERSON <>", value, "lastmodifiedperson");
            return (Criteria) this;
        }

        public Criteria andLastmodifiedpersonGreaterThan(String value) {
            addCriterion("LASTMODIFIEDPERSON >", value, "lastmodifiedperson");
            return (Criteria) this;
        }

        public Criteria andLastmodifiedpersonGreaterThanOrEqualTo(String value) {
            addCriterion("LASTMODIFIEDPERSON >=", value, "lastmodifiedperson");
            return (Criteria) this;
        }

        public Criteria andLastmodifiedpersonLessThan(String value) {
            addCriterion("LASTMODIFIEDPERSON <", value, "lastmodifiedperson");
            return (Criteria) this;
        }

        public Criteria andLastmodifiedpersonLessThanOrEqualTo(String value) {
            addCriterion("LASTMODIFIEDPERSON <=", value, "lastmodifiedperson");
            return (Criteria) this;
        }

        public Criteria andLastmodifiedpersonLike(String value) {
            addCriterion("LASTMODIFIEDPERSON like", value, "lastmodifiedperson");
            return (Criteria) this;
        }

        public Criteria andLastmodifiedpersonNotLike(String value) {
            addCriterion("LASTMODIFIEDPERSON not like", value, "lastmodifiedperson");
            return (Criteria) this;
        }

        public Criteria andLastmodifiedpersonIn(List<String> values) {
            addCriterion("LASTMODIFIEDPERSON in", values, "lastmodifiedperson");
            return (Criteria) this;
        }

        public Criteria andLastmodifiedpersonNotIn(List<String> values) {
            addCriterion("LASTMODIFIEDPERSON not in", values, "lastmodifiedperson");
            return (Criteria) this;
        }

        public Criteria andLastmodifiedpersonBetween(String value1, String value2) {
            addCriterion("LASTMODIFIEDPERSON between", value1, value2, "lastmodifiedperson");
            return (Criteria) this;
        }

        public Criteria andLastmodifiedpersonNotBetween(String value1, String value2) {
            addCriterion("LASTMODIFIEDPERSON not between", value1, value2, "lastmodifiedperson");
            return (Criteria) this;
        }

        public Criteria andLastmodifieddateIsNull() {
            addCriterion("LASTMODIFIEDDATE is null");
            return (Criteria) this;
        }

        public Criteria andLastmodifieddateIsNotNull() {
            addCriterion("LASTMODIFIEDDATE is not null");
            return (Criteria) this;
        }

        public Criteria andLastmodifieddateEqualTo(Date value) {
            addCriterionForJDBCDate("LASTMODIFIEDDATE =", value, "lastmodifieddate");
            return (Criteria) this;
        }

        public Criteria andLastmodifieddateNotEqualTo(Date value) {
            addCriterionForJDBCDate("LASTMODIFIEDDATE <>", value, "lastmodifieddate");
            return (Criteria) this;
        }

        public Criteria andLastmodifieddateGreaterThan(Date value) {
            addCriterionForJDBCDate("LASTMODIFIEDDATE >", value, "lastmodifieddate");
            return (Criteria) this;
        }

        public Criteria andLastmodifieddateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("LASTMODIFIEDDATE >=", value, "lastmodifieddate");
            return (Criteria) this;
        }

        public Criteria andLastmodifieddateLessThan(Date value) {
            addCriterionForJDBCDate("LASTMODIFIEDDATE <", value, "lastmodifieddate");
            return (Criteria) this;
        }

        public Criteria andLastmodifieddateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("LASTMODIFIEDDATE <=", value, "lastmodifieddate");
            return (Criteria) this;
        }

        public Criteria andLastmodifieddateIn(List<Date> values) {
            addCriterionForJDBCDate("LASTMODIFIEDDATE in", values, "lastmodifieddate");
            return (Criteria) this;
        }

        public Criteria andLastmodifieddateNotIn(List<Date> values) {
            addCriterionForJDBCDate("LASTMODIFIEDDATE not in", values, "lastmodifieddate");
            return (Criteria) this;
        }

        public Criteria andLastmodifieddateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("LASTMODIFIEDDATE between", value1, value2, "lastmodifieddate");
            return (Criteria) this;
        }

        public Criteria andLastmodifieddateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("LASTMODIFIEDDATE not between", value1, value2, "lastmodifieddate");
            return (Criteria) this;
        }

        public Criteria andSubjectIsNull() {
            addCriterion("SUBJECT is null");
            return (Criteria) this;
        }

        public Criteria andSubjectIsNotNull() {
            addCriterion("SUBJECT is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectEqualTo(String value) {
            addCriterion("SUBJECT =", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotEqualTo(String value) {
            addCriterion("SUBJECT <>", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectGreaterThan(String value) {
            addCriterion("SUBJECT >", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectGreaterThanOrEqualTo(String value) {
            addCriterion("SUBJECT >=", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLessThan(String value) {
            addCriterion("SUBJECT <", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLessThanOrEqualTo(String value) {
            addCriterion("SUBJECT <=", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLike(String value) {
            addCriterion("SUBJECT like", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotLike(String value) {
            addCriterion("SUBJECT not like", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectIn(List<String> values) {
            addCriterion("SUBJECT in", values, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotIn(List<String> values) {
            addCriterion("SUBJECT not in", values, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectBetween(String value1, String value2) {
            addCriterion("SUBJECT between", value1, value2, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotBetween(String value1, String value2) {
            addCriterion("SUBJECT not between", value1, value2, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectpicIsNull() {
            addCriterion("SUBJECTPIC is null");
            return (Criteria) this;
        }

        public Criteria andSubjectpicIsNotNull() {
            addCriterion("SUBJECTPIC is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectpicEqualTo(String value) {
            addCriterion("SUBJECTPIC =", value, "subjectpic");
            return (Criteria) this;
        }

        public Criteria andSubjectpicNotEqualTo(String value) {
            addCriterion("SUBJECTPIC <>", value, "subjectpic");
            return (Criteria) this;
        }

        public Criteria andSubjectpicGreaterThan(String value) {
            addCriterion("SUBJECTPIC >", value, "subjectpic");
            return (Criteria) this;
        }

        public Criteria andSubjectpicGreaterThanOrEqualTo(String value) {
            addCriterion("SUBJECTPIC >=", value, "subjectpic");
            return (Criteria) this;
        }

        public Criteria andSubjectpicLessThan(String value) {
            addCriterion("SUBJECTPIC <", value, "subjectpic");
            return (Criteria) this;
        }

        public Criteria andSubjectpicLessThanOrEqualTo(String value) {
            addCriterion("SUBJECTPIC <=", value, "subjectpic");
            return (Criteria) this;
        }

        public Criteria andSubjectpicLike(String value) {
            addCriterion("SUBJECTPIC like", value, "subjectpic");
            return (Criteria) this;
        }

        public Criteria andSubjectpicNotLike(String value) {
            addCriterion("SUBJECTPIC not like", value, "subjectpic");
            return (Criteria) this;
        }

        public Criteria andSubjectpicIn(List<String> values) {
            addCriterion("SUBJECTPIC in", values, "subjectpic");
            return (Criteria) this;
        }

        public Criteria andSubjectpicNotIn(List<String> values) {
            addCriterion("SUBJECTPIC not in", values, "subjectpic");
            return (Criteria) this;
        }

        public Criteria andSubjectpicBetween(String value1, String value2) {
            addCriterion("SUBJECTPIC between", value1, value2, "subjectpic");
            return (Criteria) this;
        }

        public Criteria andSubjectpicNotBetween(String value1, String value2) {
            addCriterion("SUBJECTPIC not between", value1, value2, "subjectpic");
            return (Criteria) this;
        }

        public Criteria andSubtext1IsNull() {
            addCriterion("SUBTEXT1 is null");
            return (Criteria) this;
        }

        public Criteria andSubtext1IsNotNull() {
            addCriterion("SUBTEXT1 is not null");
            return (Criteria) this;
        }

        public Criteria andSubtext1EqualTo(String value) {
            addCriterion("SUBTEXT1 =", value, "subtext1");
            return (Criteria) this;
        }

        public Criteria andSubtext1NotEqualTo(String value) {
            addCriterion("SUBTEXT1 <>", value, "subtext1");
            return (Criteria) this;
        }

        public Criteria andSubtext1GreaterThan(String value) {
            addCriterion("SUBTEXT1 >", value, "subtext1");
            return (Criteria) this;
        }

        public Criteria andSubtext1GreaterThanOrEqualTo(String value) {
            addCriterion("SUBTEXT1 >=", value, "subtext1");
            return (Criteria) this;
        }

        public Criteria andSubtext1LessThan(String value) {
            addCriterion("SUBTEXT1 <", value, "subtext1");
            return (Criteria) this;
        }

        public Criteria andSubtext1LessThanOrEqualTo(String value) {
            addCriterion("SUBTEXT1 <=", value, "subtext1");
            return (Criteria) this;
        }

        public Criteria andSubtext1Like(String value) {
            addCriterion("SUBTEXT1 like", value, "subtext1");
            return (Criteria) this;
        }

        public Criteria andSubtext1NotLike(String value) {
            addCriterion("SUBTEXT1 not like", value, "subtext1");
            return (Criteria) this;
        }

        public Criteria andSubtext1In(List<String> values) {
            addCriterion("SUBTEXT1 in", values, "subtext1");
            return (Criteria) this;
        }

        public Criteria andSubtext1NotIn(List<String> values) {
            addCriterion("SUBTEXT1 not in", values, "subtext1");
            return (Criteria) this;
        }

        public Criteria andSubtext1Between(String value1, String value2) {
            addCriterion("SUBTEXT1 between", value1, value2, "subtext1");
            return (Criteria) this;
        }

        public Criteria andSubtext1NotBetween(String value1, String value2) {
            addCriterion("SUBTEXT1 not between", value1, value2, "subtext1");
            return (Criteria) this;
        }

        public Criteria andSubtext2IsNull() {
            addCriterion("SUBTEXT2 is null");
            return (Criteria) this;
        }

        public Criteria andSubtext2IsNotNull() {
            addCriterion("SUBTEXT2 is not null");
            return (Criteria) this;
        }

        public Criteria andSubtext2EqualTo(String value) {
            addCriterion("SUBTEXT2 =", value, "subtext2");
            return (Criteria) this;
        }

        public Criteria andSubtext2NotEqualTo(String value) {
            addCriterion("SUBTEXT2 <>", value, "subtext2");
            return (Criteria) this;
        }

        public Criteria andSubtext2GreaterThan(String value) {
            addCriterion("SUBTEXT2 >", value, "subtext2");
            return (Criteria) this;
        }

        public Criteria andSubtext2GreaterThanOrEqualTo(String value) {
            addCriterion("SUBTEXT2 >=", value, "subtext2");
            return (Criteria) this;
        }

        public Criteria andSubtext2LessThan(String value) {
            addCriterion("SUBTEXT2 <", value, "subtext2");
            return (Criteria) this;
        }

        public Criteria andSubtext2LessThanOrEqualTo(String value) {
            addCriterion("SUBTEXT2 <=", value, "subtext2");
            return (Criteria) this;
        }

        public Criteria andSubtext2Like(String value) {
            addCriterion("SUBTEXT2 like", value, "subtext2");
            return (Criteria) this;
        }

        public Criteria andSubtext2NotLike(String value) {
            addCriterion("SUBTEXT2 not like", value, "subtext2");
            return (Criteria) this;
        }

        public Criteria andSubtext2In(List<String> values) {
            addCriterion("SUBTEXT2 in", values, "subtext2");
            return (Criteria) this;
        }

        public Criteria andSubtext2NotIn(List<String> values) {
            addCriterion("SUBTEXT2 not in", values, "subtext2");
            return (Criteria) this;
        }

        public Criteria andSubtext2Between(String value1, String value2) {
            addCriterion("SUBTEXT2 between", value1, value2, "subtext2");
            return (Criteria) this;
        }

        public Criteria andSubtext2NotBetween(String value1, String value2) {
            addCriterion("SUBTEXT2 not between", value1, value2, "subtext2");
            return (Criteria) this;
        }

        public Criteria andBodytextIsNull() {
            addCriterion("BODYTEXT is null");
            return (Criteria) this;
        }

        public Criteria andBodytextIsNotNull() {
            addCriterion("BODYTEXT is not null");
            return (Criteria) this;
        }

        public Criteria andBodytextEqualTo(String value) {
            addCriterion("BODYTEXT =", value, "bodytext");
            return (Criteria) this;
        }

        public Criteria andBodytextNotEqualTo(String value) {
            addCriterion("BODYTEXT <>", value, "bodytext");
            return (Criteria) this;
        }

        public Criteria andBodytextGreaterThan(String value) {
            addCriterion("BODYTEXT >", value, "bodytext");
            return (Criteria) this;
        }

        public Criteria andBodytextGreaterThanOrEqualTo(String value) {
            addCriterion("BODYTEXT >=", value, "bodytext");
            return (Criteria) this;
        }

        public Criteria andBodytextLessThan(String value) {
            addCriterion("BODYTEXT <", value, "bodytext");
            return (Criteria) this;
        }

        public Criteria andBodytextLessThanOrEqualTo(String value) {
            addCriterion("BODYTEXT <=", value, "bodytext");
            return (Criteria) this;
        }

        public Criteria andBodytextLike(String value) {
            addCriterion("BODYTEXT like", value, "bodytext");
            return (Criteria) this;
        }

        public Criteria andBodytextNotLike(String value) {
            addCriterion("BODYTEXT not like", value, "bodytext");
            return (Criteria) this;
        }

        public Criteria andBodytextIn(List<String> values) {
            addCriterion("BODYTEXT in", values, "bodytext");
            return (Criteria) this;
        }

        public Criteria andBodytextNotIn(List<String> values) {
            addCriterion("BODYTEXT not in", values, "bodytext");
            return (Criteria) this;
        }

        public Criteria andBodytextBetween(String value1, String value2) {
            addCriterion("BODYTEXT between", value1, value2, "bodytext");
            return (Criteria) this;
        }

        public Criteria andBodytextNotBetween(String value1, String value2) {
            addCriterion("BODYTEXT not between", value1, value2, "bodytext");
            return (Criteria) this;
        }

        public Criteria andBodypicIsNull() {
            addCriterion("BODYPIC is null");
            return (Criteria) this;
        }

        public Criteria andBodypicIsNotNull() {
            addCriterion("BODYPIC is not null");
            return (Criteria) this;
        }

        public Criteria andBodypicEqualTo(String value) {
            addCriterion("BODYPIC =", value, "bodypic");
            return (Criteria) this;
        }

        public Criteria andBodypicNotEqualTo(String value) {
            addCriterion("BODYPIC <>", value, "bodypic");
            return (Criteria) this;
        }

        public Criteria andBodypicGreaterThan(String value) {
            addCriterion("BODYPIC >", value, "bodypic");
            return (Criteria) this;
        }

        public Criteria andBodypicGreaterThanOrEqualTo(String value) {
            addCriterion("BODYPIC >=", value, "bodypic");
            return (Criteria) this;
        }

        public Criteria andBodypicLessThan(String value) {
            addCriterion("BODYPIC <", value, "bodypic");
            return (Criteria) this;
        }

        public Criteria andBodypicLessThanOrEqualTo(String value) {
            addCriterion("BODYPIC <=", value, "bodypic");
            return (Criteria) this;
        }

        public Criteria andBodypicLike(String value) {
            addCriterion("BODYPIC like", value, "bodypic");
            return (Criteria) this;
        }

        public Criteria andBodypicNotLike(String value) {
            addCriterion("BODYPIC not like", value, "bodypic");
            return (Criteria) this;
        }

        public Criteria andBodypicIn(List<String> values) {
            addCriterion("BODYPIC in", values, "bodypic");
            return (Criteria) this;
        }

        public Criteria andBodypicNotIn(List<String> values) {
            addCriterion("BODYPIC not in", values, "bodypic");
            return (Criteria) this;
        }

        public Criteria andBodypicBetween(String value1, String value2) {
            addCriterion("BODYPIC between", value1, value2, "bodypic");
            return (Criteria) this;
        }

        public Criteria andBodypicNotBetween(String value1, String value2) {
            addCriterion("BODYPIC not between", value1, value2, "bodypic");
            return (Criteria) this;
        }

        public Criteria andBodytext2IsNull() {
            addCriterion("BODYTEXT2 is null");
            return (Criteria) this;
        }

        public Criteria andBodytext2IsNotNull() {
            addCriterion("BODYTEXT2 is not null");
            return (Criteria) this;
        }

        public Criteria andBodytext2EqualTo(String value) {
            addCriterion("BODYTEXT2 =", value, "bodytext2");
            return (Criteria) this;
        }

        public Criteria andBodytext2NotEqualTo(String value) {
            addCriterion("BODYTEXT2 <>", value, "bodytext2");
            return (Criteria) this;
        }

        public Criteria andBodytext2GreaterThan(String value) {
            addCriterion("BODYTEXT2 >", value, "bodytext2");
            return (Criteria) this;
        }

        public Criteria andBodytext2GreaterThanOrEqualTo(String value) {
            addCriterion("BODYTEXT2 >=", value, "bodytext2");
            return (Criteria) this;
        }

        public Criteria andBodytext2LessThan(String value) {
            addCriterion("BODYTEXT2 <", value, "bodytext2");
            return (Criteria) this;
        }

        public Criteria andBodytext2LessThanOrEqualTo(String value) {
            addCriterion("BODYTEXT2 <=", value, "bodytext2");
            return (Criteria) this;
        }

        public Criteria andBodytext2Like(String value) {
            addCriterion("BODYTEXT2 like", value, "bodytext2");
            return (Criteria) this;
        }

        public Criteria andBodytext2NotLike(String value) {
            addCriterion("BODYTEXT2 not like", value, "bodytext2");
            return (Criteria) this;
        }

        public Criteria andBodytext2In(List<String> values) {
            addCriterion("BODYTEXT2 in", values, "bodytext2");
            return (Criteria) this;
        }

        public Criteria andBodytext2NotIn(List<String> values) {
            addCriterion("BODYTEXT2 not in", values, "bodytext2");
            return (Criteria) this;
        }

        public Criteria andBodytext2Between(String value1, String value2) {
            addCriterion("BODYTEXT2 between", value1, value2, "bodytext2");
            return (Criteria) this;
        }

        public Criteria andBodytext2NotBetween(String value1, String value2) {
            addCriterion("BODYTEXT2 not between", value1, value2, "bodytext2");
            return (Criteria) this;
        }

        public Criteria andShowhomebannerIsNull() {
            addCriterion("SHOWHOMEBANNER is null");
            return (Criteria) this;
        }

        public Criteria andShowhomebannerIsNotNull() {
            addCriterion("SHOWHOMEBANNER is not null");
            return (Criteria) this;
        }

        public Criteria andShowhomebannerEqualTo(String value) {
            addCriterion("SHOWHOMEBANNER =", value, "showhomebanner");
            return (Criteria) this;
        }

        public Criteria andShowhomebannerNotEqualTo(String value) {
            addCriterion("SHOWHOMEBANNER <>", value, "showhomebanner");
            return (Criteria) this;
        }

        public Criteria andShowhomebannerGreaterThan(String value) {
            addCriterion("SHOWHOMEBANNER >", value, "showhomebanner");
            return (Criteria) this;
        }

        public Criteria andShowhomebannerGreaterThanOrEqualTo(String value) {
            addCriterion("SHOWHOMEBANNER >=", value, "showhomebanner");
            return (Criteria) this;
        }

        public Criteria andShowhomebannerLessThan(String value) {
            addCriterion("SHOWHOMEBANNER <", value, "showhomebanner");
            return (Criteria) this;
        }

        public Criteria andShowhomebannerLessThanOrEqualTo(String value) {
            addCriterion("SHOWHOMEBANNER <=", value, "showhomebanner");
            return (Criteria) this;
        }

        public Criteria andShowhomebannerLike(String value) {
            addCriterion("SHOWHOMEBANNER like", value, "showhomebanner");
            return (Criteria) this;
        }

        public Criteria andShowhomebannerNotLike(String value) {
            addCriterion("SHOWHOMEBANNER not like", value, "showhomebanner");
            return (Criteria) this;
        }

        public Criteria andShowhomebannerIn(List<String> values) {
            addCriterion("SHOWHOMEBANNER in", values, "showhomebanner");
            return (Criteria) this;
        }

        public Criteria andShowhomebannerNotIn(List<String> values) {
            addCriterion("SHOWHOMEBANNER not in", values, "showhomebanner");
            return (Criteria) this;
        }

        public Criteria andShowhomebannerBetween(String value1, String value2) {
            addCriterion("SHOWHOMEBANNER between", value1, value2, "showhomebanner");
            return (Criteria) this;
        }

        public Criteria andShowhomebannerNotBetween(String value1, String value2) {
            addCriterion("SHOWHOMEBANNER not between", value1, value2, "showhomebanner");
            return (Criteria) this;
        }

        public Criteria andShowrecommandIsNull() {
            addCriterion("SHOWRECOMMAND is null");
            return (Criteria) this;
        }

        public Criteria andShowrecommandIsNotNull() {
            addCriterion("SHOWRECOMMAND is not null");
            return (Criteria) this;
        }

        public Criteria andShowrecommandEqualTo(String value) {
            addCriterion("SHOWRECOMMAND =", value, "showrecommand");
            return (Criteria) this;
        }

        public Criteria andShowrecommandNotEqualTo(String value) {
            addCriterion("SHOWRECOMMAND <>", value, "showrecommand");
            return (Criteria) this;
        }

        public Criteria andShowrecommandGreaterThan(String value) {
            addCriterion("SHOWRECOMMAND >", value, "showrecommand");
            return (Criteria) this;
        }

        public Criteria andShowrecommandGreaterThanOrEqualTo(String value) {
            addCriterion("SHOWRECOMMAND >=", value, "showrecommand");
            return (Criteria) this;
        }

        public Criteria andShowrecommandLessThan(String value) {
            addCriterion("SHOWRECOMMAND <", value, "showrecommand");
            return (Criteria) this;
        }

        public Criteria andShowrecommandLessThanOrEqualTo(String value) {
            addCriterion("SHOWRECOMMAND <=", value, "showrecommand");
            return (Criteria) this;
        }

        public Criteria andShowrecommandLike(String value) {
            addCriterion("SHOWRECOMMAND like", value, "showrecommand");
            return (Criteria) this;
        }

        public Criteria andShowrecommandNotLike(String value) {
            addCriterion("SHOWRECOMMAND not like", value, "showrecommand");
            return (Criteria) this;
        }

        public Criteria andShowrecommandIn(List<String> values) {
            addCriterion("SHOWRECOMMAND in", values, "showrecommand");
            return (Criteria) this;
        }

        public Criteria andShowrecommandNotIn(List<String> values) {
            addCriterion("SHOWRECOMMAND not in", values, "showrecommand");
            return (Criteria) this;
        }

        public Criteria andShowrecommandBetween(String value1, String value2) {
            addCriterion("SHOWRECOMMAND between", value1, value2, "showrecommand");
            return (Criteria) this;
        }

        public Criteria andShowrecommandNotBetween(String value1, String value2) {
            addCriterion("SHOWRECOMMAND not between", value1, value2, "showrecommand");
            return (Criteria) this;
        }

        public Criteria andShowneweventIsNull() {
            addCriterion("SHOWNEWEVENT is null");
            return (Criteria) this;
        }

        public Criteria andShowneweventIsNotNull() {
            addCriterion("SHOWNEWEVENT is not null");
            return (Criteria) this;
        }

        public Criteria andShowneweventEqualTo(String value) {
            addCriterion("SHOWNEWEVENT =", value, "shownewevent");
            return (Criteria) this;
        }

        public Criteria andShowneweventNotEqualTo(String value) {
            addCriterion("SHOWNEWEVENT <>", value, "shownewevent");
            return (Criteria) this;
        }

        public Criteria andShowneweventGreaterThan(String value) {
            addCriterion("SHOWNEWEVENT >", value, "shownewevent");
            return (Criteria) this;
        }

        public Criteria andShowneweventGreaterThanOrEqualTo(String value) {
            addCriterion("SHOWNEWEVENT >=", value, "shownewevent");
            return (Criteria) this;
        }

        public Criteria andShowneweventLessThan(String value) {
            addCriterion("SHOWNEWEVENT <", value, "shownewevent");
            return (Criteria) this;
        }

        public Criteria andShowneweventLessThanOrEqualTo(String value) {
            addCriterion("SHOWNEWEVENT <=", value, "shownewevent");
            return (Criteria) this;
        }

        public Criteria andShowneweventLike(String value) {
            addCriterion("SHOWNEWEVENT like", value, "shownewevent");
            return (Criteria) this;
        }

        public Criteria andShowneweventNotLike(String value) {
            addCriterion("SHOWNEWEVENT not like", value, "shownewevent");
            return (Criteria) this;
        }

        public Criteria andShowneweventIn(List<String> values) {
            addCriterion("SHOWNEWEVENT in", values, "shownewevent");
            return (Criteria) this;
        }

        public Criteria andShowneweventNotIn(List<String> values) {
            addCriterion("SHOWNEWEVENT not in", values, "shownewevent");
            return (Criteria) this;
        }

        public Criteria andShowneweventBetween(String value1, String value2) {
            addCriterion("SHOWNEWEVENT between", value1, value2, "shownewevent");
            return (Criteria) this;
        }

        public Criteria andShowneweventNotBetween(String value1, String value2) {
            addCriterion("SHOWNEWEVENT not between", value1, value2, "shownewevent");
            return (Criteria) this;
        }

        public Criteria andShowprogramIsNull() {
            addCriterion("SHOWPROGRAM is null");
            return (Criteria) this;
        }

        public Criteria andShowprogramIsNotNull() {
            addCriterion("SHOWPROGRAM is not null");
            return (Criteria) this;
        }

        public Criteria andShowprogramEqualTo(String value) {
            addCriterion("SHOWPROGRAM =", value, "showprogram");
            return (Criteria) this;
        }

        public Criteria andShowprogramNotEqualTo(String value) {
            addCriterion("SHOWPROGRAM <>", value, "showprogram");
            return (Criteria) this;
        }

        public Criteria andShowprogramGreaterThan(String value) {
            addCriterion("SHOWPROGRAM >", value, "showprogram");
            return (Criteria) this;
        }

        public Criteria andShowprogramGreaterThanOrEqualTo(String value) {
            addCriterion("SHOWPROGRAM >=", value, "showprogram");
            return (Criteria) this;
        }

        public Criteria andShowprogramLessThan(String value) {
            addCriterion("SHOWPROGRAM <", value, "showprogram");
            return (Criteria) this;
        }

        public Criteria andShowprogramLessThanOrEqualTo(String value) {
            addCriterion("SHOWPROGRAM <=", value, "showprogram");
            return (Criteria) this;
        }

        public Criteria andShowprogramLike(String value) {
            addCriterion("SHOWPROGRAM like", value, "showprogram");
            return (Criteria) this;
        }

        public Criteria andShowprogramNotLike(String value) {
            addCriterion("SHOWPROGRAM not like", value, "showprogram");
            return (Criteria) this;
        }

        public Criteria andShowprogramIn(List<String> values) {
            addCriterion("SHOWPROGRAM in", values, "showprogram");
            return (Criteria) this;
        }

        public Criteria andShowprogramNotIn(List<String> values) {
            addCriterion("SHOWPROGRAM not in", values, "showprogram");
            return (Criteria) this;
        }

        public Criteria andShowprogramBetween(String value1, String value2) {
            addCriterion("SHOWPROGRAM between", value1, value2, "showprogram");
            return (Criteria) this;
        }

        public Criteria andShowprogramNotBetween(String value1, String value2) {
            addCriterion("SHOWPROGRAM not between", value1, value2, "showprogram");
            return (Criteria) this;
        }

        public Criteria andShowpushmessageIsNull() {
            addCriterion("SHOWPUSHMESSAGE is null");
            return (Criteria) this;
        }

        public Criteria andShowpushmessageIsNotNull() {
            addCriterion("SHOWPUSHMESSAGE is not null");
            return (Criteria) this;
        }

        public Criteria andShowpushmessageEqualTo(String value) {
            addCriterion("SHOWPUSHMESSAGE =", value, "showpushmessage");
            return (Criteria) this;
        }

        public Criteria andShowpushmessageNotEqualTo(String value) {
            addCriterion("SHOWPUSHMESSAGE <>", value, "showpushmessage");
            return (Criteria) this;
        }

        public Criteria andShowpushmessageGreaterThan(String value) {
            addCriterion("SHOWPUSHMESSAGE >", value, "showpushmessage");
            return (Criteria) this;
        }

        public Criteria andShowpushmessageGreaterThanOrEqualTo(String value) {
            addCriterion("SHOWPUSHMESSAGE >=", value, "showpushmessage");
            return (Criteria) this;
        }

        public Criteria andShowpushmessageLessThan(String value) {
            addCriterion("SHOWPUSHMESSAGE <", value, "showpushmessage");
            return (Criteria) this;
        }

        public Criteria andShowpushmessageLessThanOrEqualTo(String value) {
            addCriterion("SHOWPUSHMESSAGE <=", value, "showpushmessage");
            return (Criteria) this;
        }

        public Criteria andShowpushmessageLike(String value) {
            addCriterion("SHOWPUSHMESSAGE like", value, "showpushmessage");
            return (Criteria) this;
        }

        public Criteria andShowpushmessageNotLike(String value) {
            addCriterion("SHOWPUSHMESSAGE not like", value, "showpushmessage");
            return (Criteria) this;
        }

        public Criteria andShowpushmessageIn(List<String> values) {
            addCriterion("SHOWPUSHMESSAGE in", values, "showpushmessage");
            return (Criteria) this;
        }

        public Criteria andShowpushmessageNotIn(List<String> values) {
            addCriterion("SHOWPUSHMESSAGE not in", values, "showpushmessage");
            return (Criteria) this;
        }

        public Criteria andShowpushmessageBetween(String value1, String value2) {
            addCriterion("SHOWPUSHMESSAGE between", value1, value2, "showpushmessage");
            return (Criteria) this;
        }

        public Criteria andShowpushmessageNotBetween(String value1, String value2) {
            addCriterion("SHOWPUSHMESSAGE not between", value1, value2, "showpushmessage");
            return (Criteria) this;
        }

        public Criteria andEffectdateIsNull() {
            addCriterion("EFFECTDATE is null");
            return (Criteria) this;
        }

        public Criteria andEffectdateIsNotNull() {
            addCriterion("EFFECTDATE is not null");
            return (Criteria) this;
        }

        public Criteria andEffectdateEqualTo(Date value) {
            addCriterionForJDBCDate("EFFECTDATE =", value, "effectdate");
            return (Criteria) this;
        }

        public Criteria andEffectdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("EFFECTDATE <>", value, "effectdate");
            return (Criteria) this;
        }

        public Criteria andEffectdateGreaterThan(Date value) {
            addCriterionForJDBCDate("EFFECTDATE >", value, "effectdate");
            return (Criteria) this;
        }

        public Criteria andEffectdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("EFFECTDATE >=", value, "effectdate");
            return (Criteria) this;
        }

        public Criteria andEffectdateLessThan(Date value) {
            addCriterionForJDBCDate("EFFECTDATE <", value, "effectdate");
            return (Criteria) this;
        }

        public Criteria andEffectdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("EFFECTDATE <=", value, "effectdate");
            return (Criteria) this;
        }

        public Criteria andEffectdateIn(List<Date> values) {
            addCriterionForJDBCDate("EFFECTDATE in", values, "effectdate");
            return (Criteria) this;
        }

        public Criteria andEffectdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("EFFECTDATE not in", values, "effectdate");
            return (Criteria) this;
        }

        public Criteria andEffectdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("EFFECTDATE between", value1, value2, "effectdate");
            return (Criteria) this;
        }

        public Criteria andEffectdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("EFFECTDATE not between", value1, value2, "effectdate");
            return (Criteria) this;
        }

        public Criteria andExpiredateIsNull() {
            addCriterion("EXPIREDATE is null");
            return (Criteria) this;
        }

        public Criteria andExpiredateIsNotNull() {
            addCriterion("EXPIREDATE is not null");
            return (Criteria) this;
        }

        public Criteria andExpiredateEqualTo(Date value) {
            addCriterionForJDBCDate("EXPIREDATE =", value, "expiredate");
            return (Criteria) this;
        }

        public Criteria andExpiredateNotEqualTo(Date value) {
            addCriterionForJDBCDate("EXPIREDATE <>", value, "expiredate");
            return (Criteria) this;
        }

        public Criteria andExpiredateGreaterThan(Date value) {
            addCriterionForJDBCDate("EXPIREDATE >", value, "expiredate");
            return (Criteria) this;
        }

        public Criteria andExpiredateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("EXPIREDATE >=", value, "expiredate");
            return (Criteria) this;
        }

        public Criteria andExpiredateLessThan(Date value) {
            addCriterionForJDBCDate("EXPIREDATE <", value, "expiredate");
            return (Criteria) this;
        }

        public Criteria andExpiredateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("EXPIREDATE <=", value, "expiredate");
            return (Criteria) this;
        }

        public Criteria andExpiredateIn(List<Date> values) {
            addCriterionForJDBCDate("EXPIREDATE in", values, "expiredate");
            return (Criteria) this;
        }

        public Criteria andExpiredateNotIn(List<Date> values) {
            addCriterionForJDBCDate("EXPIREDATE not in", values, "expiredate");
            return (Criteria) this;
        }

        public Criteria andExpiredateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("EXPIREDATE between", value1, value2, "expiredate");
            return (Criteria) this;
        }

        public Criteria andExpiredateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("EXPIREDATE not between", value1, value2, "expiredate");
            return (Criteria) this;
        }

        public Criteria andEffectdatehomeIsNull() {
            addCriterion("EFFECTDATEHOME is null");
            return (Criteria) this;
        }

        public Criteria andEffectdatehomeIsNotNull() {
            addCriterion("EFFECTDATEHOME is not null");
            return (Criteria) this;
        }

        public Criteria andEffectdatehomeEqualTo(Date value) {
            addCriterionForJDBCDate("EFFECTDATEHOME =", value, "effectdatehome");
            return (Criteria) this;
        }

        public Criteria andEffectdatehomeNotEqualTo(Date value) {
            addCriterionForJDBCDate("EFFECTDATEHOME <>", value, "effectdatehome");
            return (Criteria) this;
        }

        public Criteria andEffectdatehomeGreaterThan(Date value) {
            addCriterionForJDBCDate("EFFECTDATEHOME >", value, "effectdatehome");
            return (Criteria) this;
        }

        public Criteria andEffectdatehomeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("EFFECTDATEHOME >=", value, "effectdatehome");
            return (Criteria) this;
        }

        public Criteria andEffectdatehomeLessThan(Date value) {
            addCriterionForJDBCDate("EFFECTDATEHOME <", value, "effectdatehome");
            return (Criteria) this;
        }

        public Criteria andEffectdatehomeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("EFFECTDATEHOME <=", value, "effectdatehome");
            return (Criteria) this;
        }

        public Criteria andEffectdatehomeIn(List<Date> values) {
            addCriterionForJDBCDate("EFFECTDATEHOME in", values, "effectdatehome");
            return (Criteria) this;
        }

        public Criteria andEffectdatehomeNotIn(List<Date> values) {
            addCriterionForJDBCDate("EFFECTDATEHOME not in", values, "effectdatehome");
            return (Criteria) this;
        }

        public Criteria andEffectdatehomeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("EFFECTDATEHOME between", value1, value2, "effectdatehome");
            return (Criteria) this;
        }

        public Criteria andEffectdatehomeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("EFFECTDATEHOME not between", value1, value2, "effectdatehome");
            return (Criteria) this;
        }

        public Criteria andExpiredatehomeIsNull() {
            addCriterion("EXPIREDATEHOME is null");
            return (Criteria) this;
        }

        public Criteria andExpiredatehomeIsNotNull() {
            addCriterion("EXPIREDATEHOME is not null");
            return (Criteria) this;
        }

        public Criteria andExpiredatehomeEqualTo(Date value) {
            addCriterionForJDBCDate("EXPIREDATEHOME =", value, "expiredatehome");
            return (Criteria) this;
        }

        public Criteria andExpiredatehomeNotEqualTo(Date value) {
            addCriterionForJDBCDate("EXPIREDATEHOME <>", value, "expiredatehome");
            return (Criteria) this;
        }

        public Criteria andExpiredatehomeGreaterThan(Date value) {
            addCriterionForJDBCDate("EXPIREDATEHOME >", value, "expiredatehome");
            return (Criteria) this;
        }

        public Criteria andExpiredatehomeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("EXPIREDATEHOME >=", value, "expiredatehome");
            return (Criteria) this;
        }

        public Criteria andExpiredatehomeLessThan(Date value) {
            addCriterionForJDBCDate("EXPIREDATEHOME <", value, "expiredatehome");
            return (Criteria) this;
        }

        public Criteria andExpiredatehomeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("EXPIREDATEHOME <=", value, "expiredatehome");
            return (Criteria) this;
        }

        public Criteria andExpiredatehomeIn(List<Date> values) {
            addCriterionForJDBCDate("EXPIREDATEHOME in", values, "expiredatehome");
            return (Criteria) this;
        }

        public Criteria andExpiredatehomeNotIn(List<Date> values) {
            addCriterionForJDBCDate("EXPIREDATEHOME not in", values, "expiredatehome");
            return (Criteria) this;
        }

        public Criteria andExpiredatehomeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("EXPIREDATEHOME between", value1, value2, "expiredatehome");
            return (Criteria) this;
        }

        public Criteria andExpiredatehomeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("EXPIREDATEHOME not between", value1, value2, "expiredatehome");
            return (Criteria) this;
        }

        public Criteria andEffectdaterecommandIsNull() {
            addCriterion("EFFECTDATERECOMMAND is null");
            return (Criteria) this;
        }

        public Criteria andEffectdaterecommandIsNotNull() {
            addCriterion("EFFECTDATERECOMMAND is not null");
            return (Criteria) this;
        }

        public Criteria andEffectdaterecommandEqualTo(Date value) {
            addCriterionForJDBCDate("EFFECTDATERECOMMAND =", value, "effectdaterecommand");
            return (Criteria) this;
        }

        public Criteria andEffectdaterecommandNotEqualTo(Date value) {
            addCriterionForJDBCDate("EFFECTDATERECOMMAND <>", value, "effectdaterecommand");
            return (Criteria) this;
        }

        public Criteria andEffectdaterecommandGreaterThan(Date value) {
            addCriterionForJDBCDate("EFFECTDATERECOMMAND >", value, "effectdaterecommand");
            return (Criteria) this;
        }

        public Criteria andEffectdaterecommandGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("EFFECTDATERECOMMAND >=", value, "effectdaterecommand");
            return (Criteria) this;
        }

        public Criteria andEffectdaterecommandLessThan(Date value) {
            addCriterionForJDBCDate("EFFECTDATERECOMMAND <", value, "effectdaterecommand");
            return (Criteria) this;
        }

        public Criteria andEffectdaterecommandLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("EFFECTDATERECOMMAND <=", value, "effectdaterecommand");
            return (Criteria) this;
        }

        public Criteria andEffectdaterecommandIn(List<Date> values) {
            addCriterionForJDBCDate("EFFECTDATERECOMMAND in", values, "effectdaterecommand");
            return (Criteria) this;
        }

        public Criteria andEffectdaterecommandNotIn(List<Date> values) {
            addCriterionForJDBCDate("EFFECTDATERECOMMAND not in", values, "effectdaterecommand");
            return (Criteria) this;
        }

        public Criteria andEffectdaterecommandBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("EFFECTDATERECOMMAND between", value1, value2, "effectdaterecommand");
            return (Criteria) this;
        }

        public Criteria andEffectdaterecommandNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("EFFECTDATERECOMMAND not between", value1, value2, "effectdaterecommand");
            return (Criteria) this;
        }

        public Criteria andExpiredaterecommandIsNull() {
            addCriterion("EXPIREDATERECOMMAND is null");
            return (Criteria) this;
        }

        public Criteria andExpiredaterecommandIsNotNull() {
            addCriterion("EXPIREDATERECOMMAND is not null");
            return (Criteria) this;
        }

        public Criteria andExpiredaterecommandEqualTo(Date value) {
            addCriterionForJDBCDate("EXPIREDATERECOMMAND =", value, "expiredaterecommand");
            return (Criteria) this;
        }

        public Criteria andExpiredaterecommandNotEqualTo(Date value) {
            addCriterionForJDBCDate("EXPIREDATERECOMMAND <>", value, "expiredaterecommand");
            return (Criteria) this;
        }

        public Criteria andExpiredaterecommandGreaterThan(Date value) {
            addCriterionForJDBCDate("EXPIREDATERECOMMAND >", value, "expiredaterecommand");
            return (Criteria) this;
        }

        public Criteria andExpiredaterecommandGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("EXPIREDATERECOMMAND >=", value, "expiredaterecommand");
            return (Criteria) this;
        }

        public Criteria andExpiredaterecommandLessThan(Date value) {
            addCriterionForJDBCDate("EXPIREDATERECOMMAND <", value, "expiredaterecommand");
            return (Criteria) this;
        }

        public Criteria andExpiredaterecommandLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("EXPIREDATERECOMMAND <=", value, "expiredaterecommand");
            return (Criteria) this;
        }

        public Criteria andExpiredaterecommandIn(List<Date> values) {
            addCriterionForJDBCDate("EXPIREDATERECOMMAND in", values, "expiredaterecommand");
            return (Criteria) this;
        }

        public Criteria andExpiredaterecommandNotIn(List<Date> values) {
            addCriterionForJDBCDate("EXPIREDATERECOMMAND not in", values, "expiredaterecommand");
            return (Criteria) this;
        }

        public Criteria andExpiredaterecommandBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("EXPIREDATERECOMMAND between", value1, value2, "expiredaterecommand");
            return (Criteria) this;
        }

        public Criteria andExpiredaterecommandNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("EXPIREDATERECOMMAND not between", value1, value2, "expiredaterecommand");
            return (Criteria) this;
        }

        public Criteria andLinkurlIsNull() {
            addCriterion("LINKURL is null");
            return (Criteria) this;
        }

        public Criteria andLinkurlIsNotNull() {
            addCriterion("LINKURL is not null");
            return (Criteria) this;
        }

        public Criteria andLinkurlEqualTo(String value) {
            addCriterion("LINKURL =", value, "linkurl");
            return (Criteria) this;
        }

        public Criteria andLinkurlNotEqualTo(String value) {
            addCriterion("LINKURL <>", value, "linkurl");
            return (Criteria) this;
        }

        public Criteria andLinkurlGreaterThan(String value) {
            addCriterion("LINKURL >", value, "linkurl");
            return (Criteria) this;
        }

        public Criteria andLinkurlGreaterThanOrEqualTo(String value) {
            addCriterion("LINKURL >=", value, "linkurl");
            return (Criteria) this;
        }

        public Criteria andLinkurlLessThan(String value) {
            addCriterion("LINKURL <", value, "linkurl");
            return (Criteria) this;
        }

        public Criteria andLinkurlLessThanOrEqualTo(String value) {
            addCriterion("LINKURL <=", value, "linkurl");
            return (Criteria) this;
        }

        public Criteria andLinkurlLike(String value) {
            addCriterion("LINKURL like", value, "linkurl");
            return (Criteria) this;
        }

        public Criteria andLinkurlNotLike(String value) {
            addCriterion("LINKURL not like", value, "linkurl");
            return (Criteria) this;
        }

        public Criteria andLinkurlIn(List<String> values) {
            addCriterion("LINKURL in", values, "linkurl");
            return (Criteria) this;
        }

        public Criteria andLinkurlNotIn(List<String> values) {
            addCriterion("LINKURL not in", values, "linkurl");
            return (Criteria) this;
        }

        public Criteria andLinkurlBetween(String value1, String value2) {
            addCriterion("LINKURL between", value1, value2, "linkurl");
            return (Criteria) this;
        }

        public Criteria andLinkurlNotBetween(String value1, String value2) {
            addCriterion("LINKURL not between", value1, value2, "linkurl");
            return (Criteria) this;
        }

        public Criteria andServiceidIsNull() {
            addCriterion("SERVICEID is null");
            return (Criteria) this;
        }

        public Criteria andServiceidIsNotNull() {
            addCriterion("SERVICEID is not null");
            return (Criteria) this;
        }

        public Criteria andServiceidEqualTo(String value) {
            addCriterion("SERVICEID =", value, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidNotEqualTo(String value) {
            addCriterion("SERVICEID <>", value, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidGreaterThan(String value) {
            addCriterion("SERVICEID >", value, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidGreaterThanOrEqualTo(String value) {
            addCriterion("SERVICEID >=", value, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidLessThan(String value) {
            addCriterion("SERVICEID <", value, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidLessThanOrEqualTo(String value) {
            addCriterion("SERVICEID <=", value, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidLike(String value) {
            addCriterion("SERVICEID like", value, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidNotLike(String value) {
            addCriterion("SERVICEID not like", value, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidIn(List<String> values) {
            addCriterion("SERVICEID in", values, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidNotIn(List<String> values) {
            addCriterion("SERVICEID not in", values, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidBetween(String value1, String value2) {
            addCriterion("SERVICEID between", value1, value2, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidNotBetween(String value1, String value2) {
            addCriterion("SERVICEID not between", value1, value2, "serviceid");
            return (Criteria) this;
        }

        public Criteria andSortorderIsNull() {
            addCriterion("SORTORDER is null");
            return (Criteria) this;
        }

        public Criteria andSortorderIsNotNull() {
            addCriterion("SORTORDER is not null");
            return (Criteria) this;
        }

        public Criteria andSortorderEqualTo(BigDecimal value) {
            addCriterion("SORTORDER =", value, "sortorder");
            return (Criteria) this;
        }

        public Criteria andSortorderNotEqualTo(BigDecimal value) {
            addCriterion("SORTORDER <>", value, "sortorder");
            return (Criteria) this;
        }

        public Criteria andSortorderGreaterThan(BigDecimal value) {
            addCriterion("SORTORDER >", value, "sortorder");
            return (Criteria) this;
        }

        public Criteria andSortorderGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SORTORDER >=", value, "sortorder");
            return (Criteria) this;
        }

        public Criteria andSortorderLessThan(BigDecimal value) {
            addCriterion("SORTORDER <", value, "sortorder");
            return (Criteria) this;
        }

        public Criteria andSortorderLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SORTORDER <=", value, "sortorder");
            return (Criteria) this;
        }

        public Criteria andSortorderIn(List<BigDecimal> values) {
            addCriterion("SORTORDER in", values, "sortorder");
            return (Criteria) this;
        }

        public Criteria andSortorderNotIn(List<BigDecimal> values) {
            addCriterion("SORTORDER not in", values, "sortorder");
            return (Criteria) this;
        }

        public Criteria andSortorderBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SORTORDER between", value1, value2, "sortorder");
            return (Criteria) this;
        }

        public Criteria andSortorderNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SORTORDER not between", value1, value2, "sortorder");
            return (Criteria) this;
        }

        public Criteria andShowsnowleopardIsNull() {
            addCriterion("SHOWSNOWLEOPARD is null");
            return (Criteria) this;
        }

        public Criteria andShowsnowleopardIsNotNull() {
            addCriterion("SHOWSNOWLEOPARD is not null");
            return (Criteria) this;
        }

        public Criteria andShowsnowleopardEqualTo(String value) {
            addCriterion("SHOWSNOWLEOPARD =", value, "showsnowleopard");
            return (Criteria) this;
        }

        public Criteria andShowsnowleopardNotEqualTo(String value) {
            addCriterion("SHOWSNOWLEOPARD <>", value, "showsnowleopard");
            return (Criteria) this;
        }

        public Criteria andShowsnowleopardGreaterThan(String value) {
            addCriterion("SHOWSNOWLEOPARD >", value, "showsnowleopard");
            return (Criteria) this;
        }

        public Criteria andShowsnowleopardGreaterThanOrEqualTo(String value) {
            addCriterion("SHOWSNOWLEOPARD >=", value, "showsnowleopard");
            return (Criteria) this;
        }

        public Criteria andShowsnowleopardLessThan(String value) {
            addCriterion("SHOWSNOWLEOPARD <", value, "showsnowleopard");
            return (Criteria) this;
        }

        public Criteria andShowsnowleopardLessThanOrEqualTo(String value) {
            addCriterion("SHOWSNOWLEOPARD <=", value, "showsnowleopard");
            return (Criteria) this;
        }

        public Criteria andShowsnowleopardLike(String value) {
            addCriterion("SHOWSNOWLEOPARD like", value, "showsnowleopard");
            return (Criteria) this;
        }

        public Criteria andShowsnowleopardNotLike(String value) {
            addCriterion("SHOWSNOWLEOPARD not like", value, "showsnowleopard");
            return (Criteria) this;
        }

        public Criteria andShowsnowleopardIn(List<String> values) {
            addCriterion("SHOWSNOWLEOPARD in", values, "showsnowleopard");
            return (Criteria) this;
        }

        public Criteria andShowsnowleopardNotIn(List<String> values) {
            addCriterion("SHOWSNOWLEOPARD not in", values, "showsnowleopard");
            return (Criteria) this;
        }

        public Criteria andShowsnowleopardBetween(String value1, String value2) {
            addCriterion("SHOWSNOWLEOPARD between", value1, value2, "showsnowleopard");
            return (Criteria) this;
        }

        public Criteria andShowsnowleopardNotBetween(String value1, String value2) {
            addCriterion("SHOWSNOWLEOPARD not between", value1, value2, "showsnowleopard");
            return (Criteria) this;
        }

        public Criteria andMessageidLikeInsensitive(String value) {
            addCriterion("upper(MESSAGEID) like", value.toUpperCase(), "messageid");
            return (Criteria) this;
        }

        public Criteria andStatusLikeInsensitive(String value) {
            addCriterion("upper(STATUS) like", value.toUpperCase(), "status");
            return (Criteria) this;
        }

        public Criteria andLastmodifiedpersonLikeInsensitive(String value) {
            addCriterion("upper(LASTMODIFIEDPERSON) like", value.toUpperCase(), "lastmodifiedperson");
            return (Criteria) this;
        }

        public Criteria andSubjectLikeInsensitive(String value) {
            addCriterion("upper(SUBJECT) like", value.toUpperCase(), "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectpicLikeInsensitive(String value) {
            addCriterion("upper(SUBJECTPIC) like", value.toUpperCase(), "subjectpic");
            return (Criteria) this;
        }

        public Criteria andSubtext1LikeInsensitive(String value) {
            addCriterion("upper(SUBTEXT1) like", value.toUpperCase(), "subtext1");
            return (Criteria) this;
        }

        public Criteria andSubtext2LikeInsensitive(String value) {
            addCriterion("upper(SUBTEXT2) like", value.toUpperCase(), "subtext2");
            return (Criteria) this;
        }

        public Criteria andBodytextLikeInsensitive(String value) {
            addCriterion("upper(BODYTEXT) like", value.toUpperCase(), "bodytext");
            return (Criteria) this;
        }

        public Criteria andBodypicLikeInsensitive(String value) {
            addCriterion("upper(BODYPIC) like", value.toUpperCase(), "bodypic");
            return (Criteria) this;
        }

        public Criteria andBodytext2LikeInsensitive(String value) {
            addCriterion("upper(BODYTEXT2) like", value.toUpperCase(), "bodytext2");
            return (Criteria) this;
        }

        public Criteria andShowhomebannerLikeInsensitive(String value) {
            addCriterion("upper(SHOWHOMEBANNER) like", value.toUpperCase(), "showhomebanner");
            return (Criteria) this;
        }

        public Criteria andShowrecommandLikeInsensitive(String value) {
            addCriterion("upper(SHOWRECOMMAND) like", value.toUpperCase(), "showrecommand");
            return (Criteria) this;
        }

        public Criteria andShowneweventLikeInsensitive(String value) {
            addCriterion("upper(SHOWNEWEVENT) like", value.toUpperCase(), "shownewevent");
            return (Criteria) this;
        }

        public Criteria andShowprogramLikeInsensitive(String value) {
            addCriterion("upper(SHOWPROGRAM) like", value.toUpperCase(), "showprogram");
            return (Criteria) this;
        }

        public Criteria andShowpushmessageLikeInsensitive(String value) {
            addCriterion("upper(SHOWPUSHMESSAGE) like", value.toUpperCase(), "showpushmessage");
            return (Criteria) this;
        }

        public Criteria andLinkurlLikeInsensitive(String value) {
            addCriterion("upper(LINKURL) like", value.toUpperCase(), "linkurl");
            return (Criteria) this;
        }

        public Criteria andServiceidLikeInsensitive(String value) {
            addCriterion("upper(SERVICEID) like", value.toUpperCase(), "serviceid");
            return (Criteria) this;
        }

        public Criteria andShowsnowleopardLikeInsensitive(String value) {
            addCriterion("upper(SHOWSNOWLEOPARD) like", value.toUpperCase(), "showsnowleopard");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MV_MESSAGELIST
     *
     * @mbggenerated do_not_delete_during_merge Wed Sep 30 11:19:36 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MV_MESSAGELIST
     *
     * @mbggenerated Wed Sep 30 11:19:36 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}