package com.tstar.model.tapp;

import java.util.Date;

public class MvPushMessageRecordMain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_PUSHMESSAGERECORDMAIN.MESSAGEID
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    private String messageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_PUSHMESSAGERECORDMAIN.SERVICEID
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    private String serviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_PUSHMESSAGERECORDMAIN.SENDTYPE
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    private String sendtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_PUSHMESSAGERECORDMAIN.DEVICETYPE
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    private String devicetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_PUSHMESSAGERECORDMAIN.MESSAGETITLE
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    private String messagetitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_PUSHMESSAGERECORDMAIN.MESSAGEBODY
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    private String messagebody;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_PUSHMESSAGERECORDMAIN.SENDDATE
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    private Date senddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_PUSHMESSAGERECORDMAIN.EXPIRYDATE
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    private Date expirydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_PUSHMESSAGERECORDMAIN.LOGINID
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    private String loginid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_PUSHMESSAGERECORDMAIN.MESSAGEID
     *
     * @return the value of MV_PUSHMESSAGERECORDMAIN.MESSAGEID
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    public String getMessageid() {
        return messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_PUSHMESSAGERECORDMAIN.MESSAGEID
     *
     * @param messageid the value for MV_PUSHMESSAGERECORDMAIN.MESSAGEID
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    public void setMessageid(String messageid) {
        this.messageid = messageid == null ? null : messageid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_PUSHMESSAGERECORDMAIN.SERVICEID
     *
     * @return the value of MV_PUSHMESSAGERECORDMAIN.SERVICEID
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    public String getServiceid() {
        return serviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_PUSHMESSAGERECORDMAIN.SERVICEID
     *
     * @param serviceid the value for MV_PUSHMESSAGERECORDMAIN.SERVICEID
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    public void setServiceid(String serviceid) {
        this.serviceid = serviceid == null ? null : serviceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_PUSHMESSAGERECORDMAIN.SENDTYPE
     *
     * @return the value of MV_PUSHMESSAGERECORDMAIN.SENDTYPE
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    public String getSendtype() {
        return sendtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_PUSHMESSAGERECORDMAIN.SENDTYPE
     *
     * @param sendtype the value for MV_PUSHMESSAGERECORDMAIN.SENDTYPE
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    public void setSendtype(String sendtype) {
        this.sendtype = sendtype == null ? null : sendtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_PUSHMESSAGERECORDMAIN.DEVICETYPE
     *
     * @return the value of MV_PUSHMESSAGERECORDMAIN.DEVICETYPE
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    public String getDevicetype() {
        return devicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_PUSHMESSAGERECORDMAIN.DEVICETYPE
     *
     * @param devicetype the value for MV_PUSHMESSAGERECORDMAIN.DEVICETYPE
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    public void setDevicetype(String devicetype) {
        this.devicetype = devicetype == null ? null : devicetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_PUSHMESSAGERECORDMAIN.MESSAGETITLE
     *
     * @return the value of MV_PUSHMESSAGERECORDMAIN.MESSAGETITLE
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    public String getMessagetitle() {
        return messagetitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_PUSHMESSAGERECORDMAIN.MESSAGETITLE
     *
     * @param messagetitle the value for MV_PUSHMESSAGERECORDMAIN.MESSAGETITLE
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    public void setMessagetitle(String messagetitle) {
        this.messagetitle = messagetitle == null ? null : messagetitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_PUSHMESSAGERECORDMAIN.MESSAGEBODY
     *
     * @return the value of MV_PUSHMESSAGERECORDMAIN.MESSAGEBODY
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    public String getMessagebody() {
        return messagebody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_PUSHMESSAGERECORDMAIN.MESSAGEBODY
     *
     * @param messagebody the value for MV_PUSHMESSAGERECORDMAIN.MESSAGEBODY
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    public void setMessagebody(String messagebody) {
        this.messagebody = messagebody == null ? null : messagebody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_PUSHMESSAGERECORDMAIN.SENDDATE
     *
     * @return the value of MV_PUSHMESSAGERECORDMAIN.SENDDATE
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    public Date getSenddate() {
        return senddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_PUSHMESSAGERECORDMAIN.SENDDATE
     *
     * @param senddate the value for MV_PUSHMESSAGERECORDMAIN.SENDDATE
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    public void setSenddate(Date senddate) {
        this.senddate = senddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_PUSHMESSAGERECORDMAIN.EXPIRYDATE
     *
     * @return the value of MV_PUSHMESSAGERECORDMAIN.EXPIRYDATE
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    public Date getExpirydate() {
        return expirydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_PUSHMESSAGERECORDMAIN.EXPIRYDATE
     *
     * @param expirydate the value for MV_PUSHMESSAGERECORDMAIN.EXPIRYDATE
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    public void setExpirydate(Date expirydate) {
        this.expirydate = expirydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_PUSHMESSAGERECORDMAIN.LOGINID
     *
     * @return the value of MV_PUSHMESSAGERECORDMAIN.LOGINID
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    public String getLoginid() {
        return loginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_PUSHMESSAGERECORDMAIN.LOGINID
     *
     * @param loginid the value for MV_PUSHMESSAGERECORDMAIN.LOGINID
     *
     * @mbggenerated Thu Dec 25 14:27:49 CST 2014
     */
    public void setLoginid(String loginid) {
        this.loginid = loginid == null ? null : loginid.trim();
    }
}