package com.tstar.model.tapp;

import java.util.Date;

public class MvPushMessageUsers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_PUSHMESSAGEUSERS.SERVICEID
     *
     * @mbggenerated Tue Feb 24 16:04:12 CST 2015
     */
    private String serviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_PUSHMESSAGEUSERS.DEVICEID
     *
     * @mbggenerated Tue Feb 24 16:04:12 CST 2015
     */
    private String deviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_PUSHMESSAGEUSERS.DEVICETYPE
     *
     * @mbggenerated Tue Feb 24 16:04:12 CST 2015
     */
    private String devicetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_PUSHMESSAGEUSERS.MSISDN
     *
     * @mbggenerated Tue Feb 24 16:04:12 CST 2015
     */
    private String msisdn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_PUSHMESSAGEUSERS.CONTRACTID
     *
     * @mbggenerated Tue Feb 24 16:04:12 CST 2015
     */
    private String contractid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_PUSHMESSAGEUSERS.REGISTERDATE
     *
     * @mbggenerated Tue Feb 24 16:04:12 CST 2015
     */
    private Date registerdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_PUSHMESSAGEUSERS.ALLOWSEND
     *
     * @mbggenerated Tue Feb 24 16:04:12 CST 2015
     */
    private String allowsend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MV_PUSHMESSAGEUSERS.TOKEN
     *
     * @mbggenerated Tue Feb 24 16:04:12 CST 2015
     */
    private String token;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_PUSHMESSAGEUSERS.SERVICEID
     *
     * @return the value of MV_PUSHMESSAGEUSERS.SERVICEID
     *
     * @mbggenerated Tue Feb 24 16:04:12 CST 2015
     */
    public String getServiceid() {
        return serviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_PUSHMESSAGEUSERS.SERVICEID
     *
     * @param serviceid the value for MV_PUSHMESSAGEUSERS.SERVICEID
     *
     * @mbggenerated Tue Feb 24 16:04:12 CST 2015
     */
    public void setServiceid(String serviceid) {
        this.serviceid = serviceid == null ? null : serviceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_PUSHMESSAGEUSERS.DEVICEID
     *
     * @return the value of MV_PUSHMESSAGEUSERS.DEVICEID
     *
     * @mbggenerated Tue Feb 24 16:04:12 CST 2015
     */
    public String getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_PUSHMESSAGEUSERS.DEVICEID
     *
     * @param deviceid the value for MV_PUSHMESSAGEUSERS.DEVICEID
     *
     * @mbggenerated Tue Feb 24 16:04:12 CST 2015
     */
    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid == null ? null : deviceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_PUSHMESSAGEUSERS.DEVICETYPE
     *
     * @return the value of MV_PUSHMESSAGEUSERS.DEVICETYPE
     *
     * @mbggenerated Tue Feb 24 16:04:12 CST 2015
     */
    public String getDevicetype() {
        return devicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_PUSHMESSAGEUSERS.DEVICETYPE
     *
     * @param devicetype the value for MV_PUSHMESSAGEUSERS.DEVICETYPE
     *
     * @mbggenerated Tue Feb 24 16:04:12 CST 2015
     */
    public void setDevicetype(String devicetype) {
        this.devicetype = devicetype == null ? null : devicetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_PUSHMESSAGEUSERS.MSISDN
     *
     * @return the value of MV_PUSHMESSAGEUSERS.MSISDN
     *
     * @mbggenerated Tue Feb 24 16:04:12 CST 2015
     */
    public String getMsisdn() {
        return msisdn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_PUSHMESSAGEUSERS.MSISDN
     *
     * @param msisdn the value for MV_PUSHMESSAGEUSERS.MSISDN
     *
     * @mbggenerated Tue Feb 24 16:04:12 CST 2015
     */
    public void setMsisdn(String msisdn) {
        this.msisdn = msisdn == null ? null : msisdn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_PUSHMESSAGEUSERS.CONTRACTID
     *
     * @return the value of MV_PUSHMESSAGEUSERS.CONTRACTID
     *
     * @mbggenerated Tue Feb 24 16:04:12 CST 2015
     */
    public String getContractid() {
        return contractid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_PUSHMESSAGEUSERS.CONTRACTID
     *
     * @param contractid the value for MV_PUSHMESSAGEUSERS.CONTRACTID
     *
     * @mbggenerated Tue Feb 24 16:04:12 CST 2015
     */
    public void setContractid(String contractid) {
        this.contractid = contractid == null ? null : contractid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_PUSHMESSAGEUSERS.REGISTERDATE
     *
     * @return the value of MV_PUSHMESSAGEUSERS.REGISTERDATE
     *
     * @mbggenerated Tue Feb 24 16:04:12 CST 2015
     */
    public Date getRegisterdate() {
        return registerdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_PUSHMESSAGEUSERS.REGISTERDATE
     *
     * @param registerdate the value for MV_PUSHMESSAGEUSERS.REGISTERDATE
     *
     * @mbggenerated Tue Feb 24 16:04:12 CST 2015
     */
    public void setRegisterdate(Date registerdate) {
        this.registerdate = registerdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_PUSHMESSAGEUSERS.ALLOWSEND
     *
     * @return the value of MV_PUSHMESSAGEUSERS.ALLOWSEND
     *
     * @mbggenerated Tue Feb 24 16:04:12 CST 2015
     */
    public String getAllowsend() {
        return allowsend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_PUSHMESSAGEUSERS.ALLOWSEND
     *
     * @param allowsend the value for MV_PUSHMESSAGEUSERS.ALLOWSEND
     *
     * @mbggenerated Tue Feb 24 16:04:12 CST 2015
     */
    public void setAllowsend(String allowsend) {
        this.allowsend = allowsend == null ? null : allowsend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MV_PUSHMESSAGEUSERS.TOKEN
     *
     * @return the value of MV_PUSHMESSAGEUSERS.TOKEN
     *
     * @mbggenerated Tue Feb 24 16:04:12 CST 2015
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MV_PUSHMESSAGEUSERS.TOKEN
     *
     * @param token the value for MV_PUSHMESSAGEUSERS.TOKEN
     *
     * @mbggenerated Tue Feb 24 16:04:12 CST 2015
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }
}