package com.tstar.model.tapp;

public class Projects {
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECTS.ID
     *
     * @mbggenerated Wed Oct 01 17:36:16 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECTS.NAME
     *
     * @mbggenerated Wed Oct 01 17:36:16 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECTS.STATUS
     *
     * @mbggenerated Wed Oct 01 17:36:16 CST 2014
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECTS.DEVICE_ID
     *
     * @mbggenerated Wed Oct 01 17:36:16 CST 2014
     */
    private String deviceId;
    

	@Override
	public String toString() {
		return "Id:" + this.id +
				", Name:" + this.name + 
				", Status:" + this.status + 
				", DeviceId:" + this.deviceId;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECTS.ID
     *
     * @return the value of PROJECTS.ID
     *
     * @mbggenerated Wed Oct 01 17:36:16 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECTS.ID
     *
     * @param id the value for PROJECTS.ID
     *
     * @mbggenerated Wed Oct 01 17:36:16 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECTS.NAME
     *
     * @return the value of PROJECTS.NAME
     *
     * @mbggenerated Wed Oct 01 17:36:16 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECTS.NAME
     *
     * @param name the value for PROJECTS.NAME
     *
     * @mbggenerated Wed Oct 01 17:36:16 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECTS.STATUS
     *
     * @return the value of PROJECTS.STATUS
     *
     * @mbggenerated Wed Oct 01 17:36:16 CST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECTS.STATUS
     *
     * @param status the value for PROJECTS.STATUS
     *
     * @mbggenerated Wed Oct 01 17:36:16 CST 2014
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECTS.DEVICE_ID
     *
     * @return the value of PROJECTS.DEVICE_ID
     *
     * @mbggenerated Wed Oct 01 17:36:16 CST 2014
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECTS.DEVICE_ID
     *
     * @param deviceId the value for PROJECTS.DEVICE_ID
     *
     * @mbggenerated Wed Oct 01 17:36:16 CST 2014
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }
}