package com.tstar.model.tapp;

import java.util.Date;

public class SelectList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SELECT_LIST.ID
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SELECT_LIST.SERVICE_ID
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    private String serviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SELECT_LIST.FUNCTION_ID
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    private String functionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SELECT_LIST.PARENT_ID
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SELECT_LIST.VAL
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    private String val;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SELECT_LIST.TEXT
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SELECT_LIST.STATUS
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SELECT_LIST.INSERT_TIME
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    private Date insertTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SELECT_LIST.INSERT_USER
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    private String insertUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SELECT_LIST.UPDATE_TIME
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SELECT_LIST.UPDATE_USER
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SELECT_LIST.DESCRIPTION
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SELECT_LIST.SEQ
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    private Short seq;
    
    private Short hierarchy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SELECT_LIST.ID
     *
     * @return the value of SELECT_LIST.ID
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SELECT_LIST.ID
     *
     * @param id the value for SELECT_LIST.ID
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SELECT_LIST.SERVICE_ID
     *
     * @return the value of SELECT_LIST.SERVICE_ID
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    public String getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SELECT_LIST.SERVICE_ID
     *
     * @param serviceId the value for SELECT_LIST.SERVICE_ID
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId == null ? null : serviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SELECT_LIST.FUNCTION_ID
     *
     * @return the value of SELECT_LIST.FUNCTION_ID
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    public String getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SELECT_LIST.FUNCTION_ID
     *
     * @param functionId the value for SELECT_LIST.FUNCTION_ID
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    public void setFunctionId(String functionId) {
        this.functionId = functionId == null ? null : functionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SELECT_LIST.PARENT_ID
     *
     * @return the value of SELECT_LIST.PARENT_ID
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SELECT_LIST.PARENT_ID
     *
     * @param parentId the value for SELECT_LIST.PARENT_ID
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SELECT_LIST.VAL
     *
     * @return the value of SELECT_LIST.VAL
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    public String getVal() {
        return val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SELECT_LIST.VAL
     *
     * @param val the value for SELECT_LIST.VAL
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    public void setVal(String val) {
        this.val = val == null ? null : val.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SELECT_LIST.TEXT
     *
     * @return the value of SELECT_LIST.TEXT
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SELECT_LIST.TEXT
     *
     * @param text the value for SELECT_LIST.TEXT
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SELECT_LIST.STATUS
     *
     * @return the value of SELECT_LIST.STATUS
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SELECT_LIST.STATUS
     *
     * @param status the value for SELECT_LIST.STATUS
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SELECT_LIST.INSERT_TIME
     *
     * @return the value of SELECT_LIST.INSERT_TIME
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SELECT_LIST.INSERT_TIME
     *
     * @param insertTime the value for SELECT_LIST.INSERT_TIME
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SELECT_LIST.INSERT_USER
     *
     * @return the value of SELECT_LIST.INSERT_USER
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    public String getInsertUser() {
        return insertUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SELECT_LIST.INSERT_USER
     *
     * @param insertUser the value for SELECT_LIST.INSERT_USER
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    public void setInsertUser(String insertUser) {
        this.insertUser = insertUser == null ? null : insertUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SELECT_LIST.UPDATE_TIME
     *
     * @return the value of SELECT_LIST.UPDATE_TIME
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SELECT_LIST.UPDATE_TIME
     *
     * @param updateTime the value for SELECT_LIST.UPDATE_TIME
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SELECT_LIST.UPDATE_USER
     *
     * @return the value of SELECT_LIST.UPDATE_USER
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SELECT_LIST.UPDATE_USER
     *
     * @param updateUser the value for SELECT_LIST.UPDATE_USER
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SELECT_LIST.DESCRIPTION
     *
     * @return the value of SELECT_LIST.DESCRIPTION
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SELECT_LIST.DESCRIPTION
     *
     * @param description the value for SELECT_LIST.DESCRIPTION
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SELECT_LIST.SEQ
     *
     * @return the value of SELECT_LIST.SEQ
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    public Short getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SELECT_LIST.SEQ
     *
     * @param seq the value for SELECT_LIST.SEQ
     *
     * @mbggenerated Mon Oct 20 14:36:16 CST 2014
     */
    public void setSeq(Short seq) {
        this.seq = seq;
    }
    
    public Short getHierarchy() {
        return hierarchy;
    }
    
    public void setHierarchy(Short hierarchy) {
        this.hierarchy = hierarchy;
    }

}