package com.tstar.model.tapp;

public class TransactionLogKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION_LOG.ID
     *
     * @mbggenerated Tue Dec 08 13:42:56 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION_LOG.SEQ
     *
     * @mbggenerated Tue Dec 08 13:42:56 CST 2015
     */
    private String seq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION_LOG.ID
     *
     * @return the value of TRANSACTION_LOG.ID
     *
     * @mbggenerated Tue Dec 08 13:42:56 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION_LOG.ID
     *
     * @param id the value for TRANSACTION_LOG.ID
     *
     * @mbggenerated Tue Dec 08 13:42:56 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION_LOG.SEQ
     *
     * @return the value of TRANSACTION_LOG.SEQ
     *
     * @mbggenerated Tue Dec 08 13:42:56 CST 2015
     */
    public String getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION_LOG.SEQ
     *
     * @param seq the value for TRANSACTION_LOG.SEQ
     *
     * @mbggenerated Tue Dec 08 13:42:56 CST 2015
     */
    public void setSeq(String seq) {
        this.seq = seq == null ? null : seq.trim();
    }
}